INFO:root:Anew request came
ERROR:root:division by zero
Traceback (most recent call last):
  File "c:\Users\Sushant Gupta\Desktop\pyhton\New\loogging_exception.py", line 9, in <module>
    print(x/y)
          ~^~
ZeroDivisionError: division by zero
INFO:root:Request process is complted 
INFO:root:Anew request came
INFO:root:Request process is complted 
INFO:root:Anew request came
INFO:root:Request process is complted 
INFO:root:Anew request came
INFO:root:Request process is complted 
